services:
  - type: web
    name: email-api
    env: node
    plan: free
    buildCommand: |
      npm install
    startCommand: |
      npx ts-node render.ts
    envVars:
      - key: EMAIL_USER
        sync: false  # set in Render dashboard
      - key: EMAIL_PASS
        sync: false  # set in Render dashboard
      - key: PORT
        value: 10000
    autoDeploy: true
